from langchain.chat_models import BaseChatModel
import os
import shutil
import base64
import traceback
import pandas as pd
from ..Agent import analysis_agent, code_agent, prompt_agent
from typing import Callable
from .states import PlotAgent_InputState, PlotAgent_OutputState
from langgraph.graph import StateGraph


def prompt_node(
    llm: BaseChatModel,
) -> Callable[[PlotAgent_InputState], PlotAgent_InputState]:
    def llm_prompt_node(state: PlotAgent_InputState) -> PlotAgent_InputState:
        dataset = pd.DataFrame(state["analysis_result"])
        dataset = dataset.rename(columns={"rid": "review_id"})
        dataset_info = dataset.info()
        dataset_eg = dataset.head(1)
        response = prompt_agent(llm, dataset_info, dataset_eg, state["query"])
        return {"graph_context": response.content}

    return llm_prompt_node


def code_node(
    sandbox_graph: StateGraph, max_retries: int = 5
) -> Callable[[PlotAgent_InputState], PlotAgent_InputState]:
    def llm_code_node(state: PlotAgent_InputState) -> PlotAgent_InputState:
        attempt = 0
        last_exception = None

        while attempt < max_retries:
            python_env = None
            path = None

            try:
                attempt += 1
                print(f"\n[Attempt {attempt}/{max_retries}] Running code agent...")

                df = pd.DataFrame(state["analysis_result"])
                df = df.rename(columns={"rid": "review_id"})

                if os.path.exists(f"./temp_{state['run_id']}"):
                    shutil.rmtree(f"./temp_{state['run_id']}")

                os.makedirs(f"./temp_{state['run_id']}")

                name = f"./temp_{state['run_id']}/review_analysis.csv"
                df.to_csv(name, index=False)

                path = name

                dataset_info = df.info()
                dataset_eg = df.head(1)

                output_dir_name = f"./sandbox_output_{state['run_id']}"

                if os.path.exists(output_dir_name):
                    shutil.rmtree(output_dir_name)

                os.makedirs(output_dir_name)

                ### env declarion

                final_state = code_agent(
                    sandbox_graph,
                    path,
                    state["graph_context"],
                    output_dir_name,
                    dataset_info,
                    dataset_eg,
                    state["product_id"],
                )

                ## Env end

                artifacts = []
                if os.path.exists(output_dir_name):
                    artifacts = [
                        f
                        for f in os.listdir(output_dir_name)
                        if os.path.isfile(os.path.join(output_dir_name, f))
                    ]

                if not artifacts:
                    raise RuntimeError("No artifacts generated by code agent.")

                print(f"Artifacts generated: {artifacts}")

                if path and os.path.exists(path):
                    os.remove(path)

                return {"graph_context": final_state.content}

            except Exception as e:
                last_exception = e
                print(f"[Retry {attempt}/{max_retries}] Agent failed.")
                traceback.print_exc()

                try:
                    if python_env:
                        python_env.close()
                except Exception:
                    pass

                if path and os.path.exists(path):
                    os.remove(path)

                if os.path.exists("review_analysis.csv"):
                    os.remove("review_analysis.csv")

                if attempt >= max_retries:
                    raise RuntimeError(
                        f"Agent failed after {max_retries} retries"
                    ) from last_exception

        raise RuntimeError("Unexpected failure in retry loop")

    return llm_code_node


def analysis_node(
    llm: BaseChatModel,
) -> Callable[[PlotAgent_InputState], PlotAgent_OutputState]:
    def llm_analysis_node(state: PlotAgent_InputState) -> PlotAgent_OutputState:
        plot_graph_folder = os.path.join(
            os.getcwd(), f"sandbox_output_{state['run_id']}"
        )
        images = []
        for id, file in enumerate(os.listdir(plot_graph_folder)):
            if file.lower().endswith((".png", ".jpg", ".jpeg")):
                img_path = os.path.join(plot_graph_folder, file)
                with open(img_path, "rb") as f:
                    encoded = base64.b64encode(f.read()).decode("utf-8")
                images.append(
                    {"path": img_path, "id": id, "filename": file, "base64": encoded}
                )

        image_content = []
        image_data = "following images are present \n"
        for image in images:
            image_content.append(
                {
                    "type": "image",
                    "base64": image["base64"],
                    "mime_type": "image/jpeg",
                }
            )
            image_data += f" id : {image['id'] + 1} =>  {image['filename']}  \n"

        df = pd.DataFrame(state["analysis_result"])
        df = df.rename(columns={"rid": "review_id"})
        dataset_info = df.info()
        dataset_eg = df.head(1)
        textual_data = state["graph_context"]

        plot_result = analysis_agent(
            llm, textual_data, dataset_info, dataset_eg, image_data, image_content
        )

        plot_result = plot_result.model_dump()
        final_data = {"plots": [], "overall_insight": ""}

        for plot in plot_result["images"]:
            final_data["plots"].append(
                {
                    "path": images[plot["id"] - 1]["path"],
                    "filename": images[plot["id"] - 1]["filename"],
                    "key_insights": "\n".join(plot["key_insight"]),
                }
            )

        final_data["overall_insight"] = plot_result["overall_insight"]

        return {
            "graphical_insight": final_data["overall_insight"],
            "graphical_plots": final_data["plots"],
        }

    return llm_analysis_node
